package lk.sampath.oc.Transfers.integration.mcash;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-10-24T09:06:25.391+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "MCashServices", 
                  wsdlLocation = "file:/C:/Users/admin/git/SB_OC_Transfer/src/main/resources/wsdl/MCashServices.wsdl",
                  targetNamespace = "http://services.web.mcash.sampath.lk/") 
public class MCashServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.web.mcash.sampath.lk/", "MCashServices");
    public final static QName MCashServicesPort = new QName("http://services.web.mcash.sampath.lk/", "MCashServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/admin/git/SB_OC_Transfer/src/main/resources/wsdl/MCashServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MCashServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/admin/git/SB_OC_Transfer/src/main/resources/wsdl/MCashServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MCashServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MCashServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MCashServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MCashServices_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MCashServices_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MCashServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns MCashServices
     */
    @WebEndpoint(name = "MCashServicesPort")
    public MCashServices getMCashServicesPort() {
        return super.getPort(MCashServicesPort, MCashServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MCashServices
     */
    @WebEndpoint(name = "MCashServicesPort")
    public MCashServices getMCashServicesPort(WebServiceFeature... features) {
        return super.getPort(MCashServicesPort, MCashServices.class, features);
    }

}
