
package lk.sampath.oc.Transfers.integration.mcash;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-10-24T09:06:25.338+05:30
 * Generated source version: 3.0.2
 */

@WebFault(name = "MCashAuthenticationException", targetNamespace = "http://services.web.mcash.sampath.lk/")
public class MCashAuthenticationException_Exception extends Exception {
    
    private lk.sampath.oc.Transfers.integration.mcash.MCashAuthenticationException mCashAuthenticationException;

    public MCashAuthenticationException_Exception() {
        super();
    }
    
    public MCashAuthenticationException_Exception(String message) {
        super(message);
    }
    
    public MCashAuthenticationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MCashAuthenticationException_Exception(String message, lk.sampath.oc.Transfers.integration.mcash.MCashAuthenticationException mCashAuthenticationException) {
        super(message);
        this.mCashAuthenticationException = mCashAuthenticationException;
    }

    public MCashAuthenticationException_Exception(String message, lk.sampath.oc.Transfers.integration.mcash.MCashAuthenticationException mCashAuthenticationException, Throwable cause) {
        super(message, cause);
        this.mCashAuthenticationException = mCashAuthenticationException;
    }

    public lk.sampath.oc.Transfers.integration.mcash.MCashAuthenticationException getFaultInfo() {
        return this.mCashAuthenticationException;
    }
}
