package lk.sampath.oc.Transfers.integration.mcash;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-10-24T09:06:25.368+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://services.web.mcash.sampath.lk/", name = "MCashServices")
@XmlSeeAlso({ObjectFactory.class})
public interface MCashServices {

    @WebMethod
    @Action(input = "http://services.web.mcash.sampath.lk/MCashServices/inquireRequest", output = "http://services.web.mcash.sampath.lk/MCashServices/inquireResponse", fault = {@FaultAction(className = MCashSystemException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/inquire/Fault/MCashSystemException"), @FaultAction(className = MCashException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/inquire/Fault/MCashException"), @FaultAction(className = MCashAuthenticationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/inquire/Fault/MCashAuthenticationException"), @FaultAction(className = MCashValidationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/inquire/Fault/MCashValidationException")})
    @RequestWrapper(localName = "inquire", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.Inquire")
    @ResponseWrapper(localName = "inquireResponse", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.InquireResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<lk.sampath.oc.Transfers.integration.mcash.SearchResultInt> inquire(
        @WebParam(name = "user", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.User user,
        @WebParam(name = "inquireDataInt", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.InquireDataInt inquireDataInt
    ) throws MCashSystemException_Exception, MCashException_Exception, MCashAuthenticationException_Exception, MCashValidationException_Exception;

    @WebMethod
    @Action(input = "http://services.web.mcash.sampath.lk/MCashServices/getCommissionRequest", output = "http://services.web.mcash.sampath.lk/MCashServices/getCommissionResponse", fault = {@FaultAction(className = MCashSystemException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/getCommission/Fault/MCashSystemException"), @FaultAction(className = MCashException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/getCommission/Fault/MCashException"), @FaultAction(className = MCashAuthenticationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/getCommission/Fault/MCashAuthenticationException"), @FaultAction(className = MCashValidationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/getCommission/Fault/MCashValidationException")})
    @RequestWrapper(localName = "getCommission", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.GetCommission")
    @ResponseWrapper(localName = "getCommissionResponse", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.GetCommissionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double getCommission(
        @WebParam(name = "user", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.User user,
        @WebParam(name = "commData", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.CommissionData commData
    ) throws MCashSystemException_Exception, MCashException_Exception, MCashAuthenticationException_Exception, MCashValidationException_Exception;

    @WebMethod
    @Action(input = "http://services.web.mcash.sampath.lk/MCashServices/sendSMSRequest", output = "http://services.web.mcash.sampath.lk/MCashServices/sendSMSResponse", fault = {@FaultAction(className = MCashSystemException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/sendSMS/Fault/MCashSystemException"), @FaultAction(className = MCashException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/sendSMS/Fault/MCashException"), @FaultAction(className = MCashAuthenticationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/sendSMS/Fault/MCashAuthenticationException"), @FaultAction(className = MCashValidationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/sendSMS/Fault/MCashValidationException")})
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.SendSMS")
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.SendSMSResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sendSMS(
        @WebParam(name = "user", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.User user,
        @WebParam(name = "sms", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.SmsMessage sms
    ) throws MCashSystemException_Exception, MCashException_Exception, MCashAuthenticationException_Exception, MCashValidationException_Exception;

    @WebMethod
    @Action(input = "http://services.web.mcash.sampath.lk/MCashServices/getTransactionLimitsRequest", output = "http://services.web.mcash.sampath.lk/MCashServices/getTransactionLimitsResponse", fault = {@FaultAction(className = MCashSystemException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/getTransactionLimits/Fault/MCashSystemException"), @FaultAction(className = MCashException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/getTransactionLimits/Fault/MCashException"), @FaultAction(className = MCashAuthenticationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/getTransactionLimits/Fault/MCashAuthenticationException"), @FaultAction(className = MCashValidationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/getTransactionLimits/Fault/MCashValidationException")})
    @RequestWrapper(localName = "getTransactionLimits", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.GetTransactionLimits")
    @ResponseWrapper(localName = "getTransactionLimitsResponse", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.GetTransactionLimitsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lk.sampath.oc.Transfers.integration.mcash.TranLimits getTransactionLimits(
        @WebParam(name = "user", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.User user,
        @WebParam(name = "accountNo", targetNamespace = "")
        java.lang.String accountNo
    ) throws MCashSystemException_Exception, MCashException_Exception, MCashAuthenticationException_Exception, MCashValidationException_Exception;

    @WebMethod
    @Action(input = "http://services.web.mcash.sampath.lk/MCashServices/createRequest", output = "http://services.web.mcash.sampath.lk/MCashServices/createResponse", fault = {@FaultAction(className = MCashSystemException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/create/Fault/MCashSystemException"), @FaultAction(className = MCashException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/create/Fault/MCashException"), @FaultAction(className = MCashAuthenticationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/create/Fault/MCashAuthenticationException"), @FaultAction(className = MCashValidationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/create/Fault/MCashValidationException")})
    @RequestWrapper(localName = "create", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.CreateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lk.sampath.oc.Transfers.integration.mcash.ResultData create(
        @WebParam(name = "user", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.User user,
        @WebParam(name = "createData", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.CreateDataInt createData
    ) throws MCashSystemException_Exception, MCashException_Exception, MCashAuthenticationException_Exception, MCashValidationException_Exception;

    @WebMethod
    @Action(input = "http://services.web.mcash.sampath.lk/MCashServices/reverseRequest", output = "http://services.web.mcash.sampath.lk/MCashServices/reverseResponse", fault = {@FaultAction(className = MCashSystemException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/reverse/Fault/MCashSystemException"), @FaultAction(className = MCashException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/reverse/Fault/MCashException"), @FaultAction(className = MCashAuthenticationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/reverse/Fault/MCashAuthenticationException"), @FaultAction(className = MCashValidationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/reverse/Fault/MCashValidationException")})
    @RequestWrapper(localName = "reverse", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.Reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.ReverseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lk.sampath.oc.Transfers.integration.mcash.ResultData reverse(
        @WebParam(name = "user", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.User user,
        @WebParam(name = "reverseData", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.ReverseDataInt reverseData
    ) throws MCashSystemException_Exception, MCashException_Exception, MCashAuthenticationException_Exception, MCashValidationException_Exception;

    @WebMethod
    @Action(input = "http://services.web.mcash.sampath.lk/MCashServices/withdrawRequest", output = "http://services.web.mcash.sampath.lk/MCashServices/withdrawResponse", fault = {@FaultAction(className = MCashSystemException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/withdraw/Fault/MCashSystemException"), @FaultAction(className = MCashException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/withdraw/Fault/MCashException"), @FaultAction(className = MCashAuthenticationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/withdraw/Fault/MCashAuthenticationException"), @FaultAction(className = MCashValidationException_Exception.class, value = "http://services.web.mcash.sampath.lk/MCashServices/withdraw/Fault/MCashValidationException")})
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://services.web.mcash.sampath.lk/", className = "lk.sampath.oc.Transfers.integration.mcash.WithdrawResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lk.sampath.oc.Transfers.integration.mcash.ResultData withdraw(
        @WebParam(name = "user", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.User user,
        @WebParam(name = "withdrawData", targetNamespace = "")
        lk.sampath.oc.Transfers.integration.mcash.WithdrawDataInt withdrawData
    ) throws MCashSystemException_Exception, MCashException_Exception, MCashAuthenticationException_Exception, MCashValidationException_Exception;
}
