
package lk.sampath.oc.Transfers.integration.mcash;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-10-24T09:06:25.323+05:30
 * Generated source version: 3.0.2
 */

@WebFault(name = "MCashException", targetNamespace = "http://services.web.mcash.sampath.lk/")
public class MCashException_Exception extends Exception {
    
    private lk.sampath.oc.Transfers.integration.mcash.MCashException mCashException;

    public MCashException_Exception() {
        super();
    }
    
    public MCashException_Exception(String message) {
        super(message);
    }
    
    public MCashException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MCashException_Exception(String message, lk.sampath.oc.Transfers.integration.mcash.MCashException mCashException) {
        super(message);
        this.mCashException = mCashException;
    }

    public MCashException_Exception(String message, lk.sampath.oc.Transfers.integration.mcash.MCashException mCashException, Throwable cause) {
        super(message, cause);
        this.mCashException = mCashException;
    }

    public lk.sampath.oc.Transfers.integration.mcash.MCashException getFaultInfo() {
        return this.mCashException;
    }
}
