
package lk.sampath.oc.Transfers.integration.mcash;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-10-24T09:06:25.308+05:30
 * Generated source version: 3.0.2
 */

@WebFault(name = "MCashSystemException", targetNamespace = "http://services.web.mcash.sampath.lk/")
public class MCashSystemException_Exception extends Exception {
    
    private lk.sampath.oc.Transfers.integration.mcash.MCashSystemException mCashSystemException;

    public MCashSystemException_Exception() {
        super();
    }
    
    public MCashSystemException_Exception(String message) {
        super(message);
    }
    
    public MCashSystemException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MCashSystemException_Exception(String message, lk.sampath.oc.Transfers.integration.mcash.MCashSystemException mCashSystemException) {
        super(message);
        this.mCashSystemException = mCashSystemException;
    }

    public MCashSystemException_Exception(String message, lk.sampath.oc.Transfers.integration.mcash.MCashSystemException mCashSystemException, Throwable cause) {
        super(message, cause);
        this.mCashSystemException = mCashSystemException;
    }

    public lk.sampath.oc.Transfers.integration.mcash.MCashSystemException getFaultInfo() {
        return this.mCashSystemException;
    }
}
