
package lk.sampath.oc.Transfers.integration.mcash;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-10-24T09:06:25.353+05:30
 * Generated source version: 3.0.2
 */

@WebFault(name = "MCashValidationException", targetNamespace = "http://services.web.mcash.sampath.lk/")
public class MCashValidationException_Exception extends Exception {
    
    private lk.sampath.oc.Transfers.integration.mcash.MCashValidationException mCashValidationException;

    public MCashValidationException_Exception() {
        super();
    }
    
    public MCashValidationException_Exception(String message) {
        super(message);
    }
    
    public MCashValidationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MCashValidationException_Exception(String message, lk.sampath.oc.Transfers.integration.mcash.MCashValidationException mCashValidationException) {
        super(message);
        this.mCashValidationException = mCashValidationException;
    }

    public MCashValidationException_Exception(String message, lk.sampath.oc.Transfers.integration.mcash.MCashValidationException mCashValidationException, Throwable cause) {
        super(message, cause);
        this.mCashValidationException = mCashValidationException;
    }

    public lk.sampath.oc.Transfers.integration.mcash.MCashValidationException getFaultInfo() {
        return this.mCashValidationException;
    }
}
